vich_uploader:
    db_driver: orm

    mappings:
       destination_image:
           uri_prefix: /images/destinations
           upload_destination: '%kernel.project_dir%/public/images/destinations'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
